[changelog]
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""

footer = """
<!-- Developed with ❤️ -->
"""

trim = true
render_always = true

[git]
tag_pattern = "^v?\\d+\\.\\d+\\.\\d+$"
features_always_bump_minor = true
breaking_always_bump_major = true
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
protect_breaking_commits = false
filter_commits = false
fail_on_unmatched_commit = false
use_branch_tags = false
topo_order = false
topo_order_commits = true
sort_commits = "oldest"
recurse_submodules = false
commit_parsers = [
    { message = "^[bB]uild\\(deps\\)", group = "<!-- 010 -->⬆️ Dependency Updates" },
    { message = "^[fF]ix\\(deps\\)", group = "<!-- 010 -->⬆️ Dependency Updates" },
    { message = "^[cC]ore\\(deps\\)", group = "<!-- 010 -->⬆️ Dependency Updates" },
    { message = "^[aA]dd(ed)?", group = "<!-- 000 -->🚀 Features" },
    { message = "^[fF]eat(ure)?", group = "<!-- 000 -->🚀 Features" },
    { message = "^[rR]emove(d)?", group = "<!-- 001 -->🗑️ Removal" },
    { message = "^[rR]efactor(ed)?", group = "<!-- 002 -->♻️ Refactor" },
    { message = "^[fF]ix(ed)?", group = "<!-- 003 -->🐛 Bug Fixes" },
    { message = "^[tT]est(ed)?", group = "<!-- 004 -->🧪 Testing" },
    { message = "^[rR]evert(ed)?", group = "<!-- 005 -->◀️ Revert" },
    { message = "^(([cC][iI][cC][dD])|([cC][iI])|([cC][dD]))", group = "<!-- 006 -->🚀 CI/CD" },
    { message = "^[dD]oc(s?)", group = "<!-- 007 -->📚 Documentation" },
    { message = ".*", group = "<!-- 099 -->⚙️ Other" },
]